#export CC=/usr/bin/clang
#export CXX=/usr/bin/clang++
export BULLET_PHYSICS_ROOT_DIR=/home/hangyin/workspace/bullet3
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/Bullet3Common:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/Bullet3Dynamics:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/Bullet3Geometry:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/Bullet3OpenCL:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/Bullet3OpenCL_clew:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/BulletCollision:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/BulletDynamics:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/BulletInverseDynamics:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/BulletSoftBody:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/src/LinearMath:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$BULLET_PHYSICS_ROOT_DIR/build_cmake/examples/OpenGLWindow:$LD_LIBRARY_PATH